# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the jepidemic generated R library.
#
# Java Epidemic
# Version: 0.03
# Generated: 2021-11-06T14:23:49.380636
# Contact: rc538@exeter.ac.uk
CoriEstimator = R6::R6Class("CoriEstimator", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	legacySupport = function(on) {
		# copy parameters
		tmp_on = self$.api$.toJava$boolean(on);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="legacySupport" , tmp_on); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	selectSpecificWindow = function(window) {
		# copy parameters
		tmp_window = self$.api$.toJava$int(window);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="selectSpecificWindow" , tmp_window); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	selectAdaptiveWindow = function(incidenceSum, minWindow) {
		# copy parameters
		tmp_incidenceSum = self$.api$.toJava$double(incidenceSum);
		tmp_minWindow = self$.api$.toJava$int(minWindow);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="selectAdaptiveWindow" , tmp_incidenceSum, tmp_minWindow); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	selectMinimumUncertainty = function(timeVsRt, minWindow) {
		# copy parameters
		tmp_timeVsRt = self$.api$.toJava$double(timeVsRt);
		tmp_minWindow = self$.api$.toJava$int(minWindow);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="selectMinimumUncertainty" , tmp_timeVsRt, tmp_minWindow); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	selectMixtureCombination = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="selectMixtureCombination" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withDefaultPrior = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="withDefaultPrior" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withFixedPrior = function(mean, sd) {
		# copy parameters
		tmp_mean = self$.api$.toJava$double(mean);
		tmp_sd = self$.api$.toJava$double(sd);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="withFixedPrior" , tmp_mean, tmp_sd); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withAdaptivePrior = function(factor) {
		# copy parameters
		tmp_factor = self$.api$.toJava$double(factor);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="withAdaptivePrior" , tmp_factor); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	collectResampledQuantiles = function(sampleSize) {
		# copy parameters
		tmp_sampleSize = self$.api$.toJava$int(sampleSize);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="collectResampledQuantiles" , tmp_sampleSize); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	collectMixtureQuantiles = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="collectMixtureQuantiles" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	collectMixtureApproximation = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="collectMixtureApproximation" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	detailedOutput = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="detailedOutput" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withInfectivityProfile = function(infectivityProfile, replace) {
		# copy parameters
		tmp_infectivityProfile = self$.api$.toJava$RNumericVector(infectivityProfile);
		tmp_replace = self$.api$.toJava$boolean(replace);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="withInfectivityProfile" , tmp_infectivityProfile, tmp_replace); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withInfectivityProfileMatrix = function(infectivityProfiles) {
		# copy parameters
		tmp_infectivityProfiles = self$.api$.toJava$RNumericArray(infectivityProfiles);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="withInfectivityProfileMatrix" , tmp_infectivityProfiles); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	atStartOfTimeseries = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="atStartOfTimeseries" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	inMiddleOfTimeseries = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/estimate/CoriEstimator;", method="inMiddleOfTimeseries" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = CoriEstimator$new(
				self$.api$.fromJava$CoriEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	estimateRt = function(incidence, dateColName, incidenceColName) {
		# copy parameters
		tmp_incidence = self$.api$.toJava$RDataframe(incidence);
		tmp_dateColName = self$.api$.toJava$String(dateColName);
		tmp_incidenceColName = self$.api$.toJava$String(incidenceColName);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="estimateRt" , tmp_incidence, tmp_dateColName, tmp_incidenceColName); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	estimateRtSingle = function(incidence, dateColName, incidenceColName) {
		# copy parameters
		tmp_incidence = self$.api$.toJava$RDataframe(incidence);
		tmp_dateColName = self$.api$.toJava$String(dateColName);
		tmp_incidenceColName = self$.api$.toJava$String(incidenceColName);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="estimateRtSingle" , tmp_incidence, tmp_dateColName, tmp_incidenceColName); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	estimateRtFromRates = function(rates, dateColName, rateColName, samplesPerProfile) {
		# copy parameters
		tmp_rates = self$.api$.toJava$RDataframe(rates);
		tmp_dateColName = self$.api$.toJava$String(dateColName);
		tmp_rateColName = self$.api$.toJava$String(rateColName);
		tmp_samplesPerProfile = self$.api$.toJava$int(samplesPerProfile);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="estimateRtFromRates" , tmp_rates, tmp_dateColName, tmp_rateColName, tmp_samplesPerProfile); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	estimateRtFromSingleRate = function(rate, dateColName, rateColName, samplesPerProfile) {
		# copy parameters
		tmp_rate = self$.api$.toJava$RDataframe(rate);
		tmp_dateColName = self$.api$.toJava$String(dateColName);
		tmp_rateColName = self$.api$.toJava$String(rateColName);
		tmp_samplesPerProfile = self$.api$.toJava$int(samplesPerProfile);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="estimateRtFromSingleRate" , tmp_rate, tmp_dateColName, tmp_rateColName, tmp_samplesPerProfile); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/jepidemic/estimate/CoriEstimator")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
