# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the jepidemic generated R library.
#
# Java Epidemic
# Version: 0.03
# Generated: 2021-11-16T09:47:48.634951
# Contact: rc538@exeter.ac.uk
GrowthRateEstimator = R6::R6Class("GrowthRateEstimator", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	withOutputQuantiles = function(quantiles) {
		# copy parameters
		tmp_quantiles = self$.api$.toJava$RNumericVector(quantiles);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withOutputQuantiles" , tmp_quantiles); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withSaneDefaults = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withSaneDefaults" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withInitialIncidence = function(incidence) {
		# copy parameters
		tmp_incidence = self$.api$.toJava$double(incidence);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withInitialIncidence" , tmp_incidence); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withGaussianEstimateWeighting = function(meanTau, sdTau) {
		# copy parameters
		tmp_meanTau = self$.api$.toJava$double(meanTau);
		tmp_sdTau = self$.api$.toJava$double(sdTau);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withGaussianEstimateWeighting" , tmp_meanTau, tmp_sdTau); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withEstimateWeighting = function(weights) {
		# copy parameters
		tmp_weights = self$.api$.toJava$RNumericVector(weights);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withEstimateWeighting" , tmp_weights); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	combineEstimatesWithWeightedMixture = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="combineEstimatesWithWeightedMixture" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	priorIncidenceFromPreviousPosterior = function(multiplyingSDby) {
		# copy parameters
		tmp_multiplyingSDby = self$.api$.toJava$double(multiplyingSDby);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="priorIncidenceFromPreviousPosterior" , tmp_multiplyingSDby); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	priorIncidenceFromScaledPreviousPosterior = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="priorIncidenceFromScaledPreviousPosterior" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	priorIncidenceFromPosteriorAndGrowthRate = function(multiplyingSDby) {
		# copy parameters
		tmp_multiplyingSDby = self$.api$.toJava$double(multiplyingSDby);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="priorIncidenceFromPosteriorAndGrowthRate" , tmp_multiplyingSDby); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	priorIncidenceFromScaledPosteriorAndGrowthRate = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="priorIncidenceFromScaledPosteriorAndGrowthRate" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	useAllPosteriorEstimates = function() {
		# copy parameters
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="useAllPosteriorEstimates" ); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	usePosteriorEstimatesFromOneWindow = function(tau) {
		# copy parameters
		tmp_tau = self$.api$.toJava$int(tau);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="usePosteriorEstimatesFromOneWindow" , tmp_tau); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	usePosteriorEstimatesWithEnoughData = function(sumIncidence) {
		# copy parameters
		tmp_sumIncidence = self$.api$.toJava$int(sumIncidence);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="usePosteriorEstimatesWithEnoughData" , tmp_sumIncidence); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withInfectivityProfile = function(infectivityProfile, replace) {
		# copy parameters
		tmp_infectivityProfile = self$.api$.toJava$RNumericVector(infectivityProfile);
		tmp_replace = self$.api$.toJava$boolean(replace);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withInfectivityProfile" , tmp_infectivityProfile, tmp_replace); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	withInfectivityProfileMatrix = function(infectivityProfiles) {
		# copy parameters
		tmp_infectivityProfiles = self$.api$.toJava$RNumericArray(infectivityProfiles);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Lorg/github/terminological/jepidemic/growth/GrowthRateEstimator;", method="withInfectivityProfileMatrix" , tmp_infectivityProfiles); 
		# is this a fluent method?
		# if(.jcall(self$.jobj, returnSig="Z", method="equals", .jcast(tmp_out))) {
		if(self$.jobj$equals(tmp_out)) {
			# return fluent method
			self$.api$printMessages()
			invisible(self)
		} else {
			# wrap return java object in R6 class  
			out = GrowthRateEstimator$new(
				self$.api$.fromJava$GrowthRateEstimator(tmp_out),
				self$.api
			);
			self$.api$printMessages()
			return(out);
		}
	},
	estimateGrowthRate = function(incidence, dateColName, incidenceColName) {
		# copy parameters
		tmp_incidence = self$.api$.toJava$RDataframe(incidence);
		tmp_dateColName = self$.api$.toJava$String(dateColName);
		tmp_incidenceColName = self$.api$.toJava$String(incidenceColName);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="estimateGrowthRate" , tmp_incidence, tmp_dateColName, tmp_incidenceColName); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	estimateGrowthRateSingle = function(incidence, dateColName, incidenceColName) {
		# copy parameters
		tmp_incidence = self$.api$.toJava$RDataframe(incidence);
		tmp_dateColName = self$.api$.toJava$String(dateColName);
		tmp_incidenceColName = self$.api$.toJava$String(incidenceColName);
		#execute method call
		tmp_out = .jcall(self$.jobj, returnSig = "Luk/co/terminological/rjava/types/RDataframe;", method="estimateGrowthRateSingle" , tmp_incidence, tmp_dateColName, tmp_incidenceColName); 
		# convert java object back to R
		out = self$.api$.fromJava$RDataframe(tmp_out);
		self$.api$printMessages()
		if(is.null(out)) return(invisible(out))
		return(out);
	},
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/jepidemic/growth/GrowthRateEstimator")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
