# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# Java Epidemic
#' R6 Bindings for Java InfectivityProfile
#'
#' @description
#' A holder of a discrete probability distribution of the infectivity profile
#' 
#' This is a class of the jepidemic generated R library.
#' 
#' Version: 0.03
#' 
#' Generated: 2022-01-28T16:04:19.693466
#'
#' @details
	#' A holder of a discrete probability distribution of the infectivity profile
#' @export
InfectivityProfile = R6::R6Class("InfectivityProfile", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new InfectivityProfile this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new InfectivityProfile object.
	#' @examples
	#' J = jepidemic::JavaApi$get();
	#' instance = J$InfectivityProfile$new(discretePdf, id)
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	
	#' @description The output of toString() of this InfectivityProfile
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this InfectivityProfile
	#' @param object The R6 instance to test for equality to this InfectivityProfile  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/jepidemic/InfectivityProfile")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
