# Generated by r6-geenrator-maven-plugin: do not edit by hand
# This is a class of the jepidemic generated R library.
#
# Java Epidemic
# Version: 0.01
# Generated: 2020-12-01T11:07:10.816225
# Contact: rc538@exeter.ac.uk
InfectivityProfile = R6::R6Class("InfectivityProfile", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	}
))
