# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a class of the jepidemic generated R library.
#
# Java Epidemic
# Version: 0.03
# Generated: 2021-11-06T14:23:49.368066
# Contact: rc538@exeter.ac.uk
InfectivityProfile = R6::R6Class("InfectivityProfile", public=list(
	.api = NULL,
	.jobj = NULL,
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	finalize = function() {
		self$.jobj = .jnull("org/github/terminological/jepidemic/InfectivityProfile")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
