---
title: "Appendix A - Cori method"
author: "Rob Challen"
date: '`r format(Sys.Date(), "%d-%m-%Y")`'
output: 
  pdf_document :
    fig_caption: yes
header-includes:
 \usepackage{float}
 \usepackage{mathtools}
 \floatplacement{figure}{H}    

knit: (function(inputFile, encoding,...) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "~/Dropbox/covid19/serial-interval/", output_file=paste0('cori-method-maths-',Sys.Date(),'.pdf')) })
fig_width: 7
fig_height: 5
out.width: "100%"
bibliography: jepidemic.bib
csl: jepidemic.csl
vignette: >
  %\VignetteIndexEntry{Cori method}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---




```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = TRUE
)
```

This appendix summarizes the 

We define the backward-looking effective reproduction number $R_t$ as the inverse ratio of the number of primary infections associated with secondary infections observed at time $t$, this is known as the instantaneous reproduction number. An alternative forward-looking definition which is easier to conceptualize, is the number of secondary infections generated by a single primary infection which occurs at time $t$, this is also known as the case reproduction number $R_t^c$ (Frazer 2007). 

Assume $I_0, I_1, \dots, I_t$ is a time series of infection counts, assumed to be drawn from some discrete probability distribution with expected value $\overline{I_t}$. $\omega_1, \omega_2, \dots, \omega_s$ is another probability distribution, the infectivity profile, that defines the likelihood that a case infected at time $t$ resulted from a case infected before time $t-s$. This definition implies that $\omega_0 = 0$, and that discrete time measures represent the upper bound of the equivalent continuous unit time interval, rather than, for example, the middle of the interval. 

$$
R_t = \frac{\overline{I_t}}{\sum_{s=1}^t \overline{I_{t-s}}\omega_s} \\
R_t^c = \sum_{s=0}^\infty{R_{t+s}}\omega_s \\
$$

Connected to the instantaneous reproduction number and the infectivity profile is the quantity $\beta$ which is the "transmissibility" of an infection in an average individual, infected at a given time, $t$, at a given number of days post infection, $\tau$. $\beta$ is related to the in host viral load of an infection, and the number of contacts that infected individuals make with susceptible individuals.

$$
\beta_{t,s} = R_t\omega_s
$$

The effective reproduction number may be defined in terms of the basic reproduction number $R_0$, the fraction of contacts that people are making at a given time $C_t$, compared to a freely mixing population, and the fraction of the population that is still susceptible to infection $S_t$.

$$
R_t = S_t C_t R_0
$$

With the definitions above we consider the number of new cases on a day $I_t$, which is the convolution of the number of cases observed in previous time points by the infectivity profile, scaled by the instantaneous reproduction number, and defining the quantity $\Lambda$ as the number of primary cases that resulted in a secondary case at time $t$. This definition disregards the possible role of co-infection, assuming secondary cases result from one, and only one, infection. 

<!-- 
N.B. thinking about weighing of the observations or adjusting for weekly periodicity. 
Don't think it can be done that easily but Lambda would be the place to incorporate it 
I think. It would be nice Lambda is possible to infer in the face of missing data?
-->

$$
\begin{aligned}
\overline{I_t} &= R_t \sum_{s=1}^t \overline{I_{t-s}}\omega_s \\
\Lambda_t &= \sum_{s=1}^t I_{t-s}\omega_s \\
E[I_t| I_0,\dots,I_{t-1},\omega,R_t] &= R_t\Lambda_t 
\end{aligned}
$$
We also assume that as a series of counts the case incidence can be represented as a Poisson distribution, $I_t \sim Pois(\lambda_t)$ and therefore $\lambda_t = \overline{I_t}$. Given the infectivity profile distribution $\omega$, the number of cases we expect to see on a given day, is given by the Poisson distribution probability density function:


$$
\begin{aligned}
P(I_t) &= \frac{\lambda_t^{I_t} e^{-\lambda_t}}{I_t!} \\
\lambda_t &\approx E[I_t| I_0,\dots,I_{t-1},\omega,R_t]\\
P(I_t | I_0,\dots,I_{t-1},\omega,R_t) &= \frac{(R_t\Lambda_t)^{I_t}e^{-R_t\Lambda_t}}{I_t!}
\end{aligned}
$$
 
We are interested in producing estimates of the reproduction number 

$$

P(I_t | I_0,\dots,I_{t-1},\omega,R_t) \times \\
P(I_{t-1} | I_0,\dots,I_{t-2},\omega,R_t)  \times  \\
P(I_{t-2} | I_0,\dots,I_{t-3},\omega,R_t)  \times  \\
\dots\\
P(I_{t-\tau} | I_0,\dots,I_{t-\tau-1},\omega,R_t) \\

$$

$$

P(A_3 | A_2,A_1)  \times P(A_2 | A_1) = \\
\frac{P(A_3,A_2,A_1)}{P(A_2,A_1)}  \times  \frac{P(A_2 , A_1)}{P(A_1)} = \\
\frac{P(A_3,A_2,A_1)}{P(A_1)} = \\
P(A_3,A_2|A_1)

$$

The likelihood of the observed incidences $I_{t-\tau+1}, \dots,I_t$ within the time period $[t-\tau+1;t]$, given what we know about preceding time periods is:

$$
\begin{aligned}
P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega,R_{t,\tau}) &= \prod_{s=t-\tau+1}^t\frac{(R_{t,\tau}\Lambda_s)^{I_s}e^{-R_{t,\tau}\Lambda_s}}{I_s!}
\\
&=
R_{t,\tau}^{\sum_{s=t-\tau+1}^t I_s}
e^{
  -R_{t,\tau}
  \big(
    \sum_{s=t-\tau+1}^t \Lambda_s
  \big)
}
\prod_{s=t-\tau+1}^t\frac{\Lambda_s^{I_s}}{I_s!}
\end{aligned}
$$
We assume $R_t$ is constant over $[t-\tau+1;t]$ (and defined as $R_{t,\tau}$). To make use of the mathematical property of the conjugate prior of the Poisson distribution, we further assume a prior belief that $R_{t,\tau}$ is Gamma distributed with shape parameter $\alpha$ and rate parameter $\beta$ and hence by definition:

$$
\begin{aligned}
P(R_{t,\tau}) = \frac{\beta^\alpha}{\Gamma(\alpha)} R_{t,\tau}^{\alpha-1}e^{-\beta R_{t,\tau}}
\end{aligned}
$$

We wish to determine the posterior probability of $R_t$ given the evidence ${I_0,\dots,I_{t},\omega,\alpha,\beta}$, i.e. we wish to identify $P(R_{t,\tau} | I_0,\dots,I_{t},\omega,\alpha,\beta)$. We have a prior probability $P(R_{t,\tau}$, and an expression for the likelihood of $I_t-\tau+1, \dots, I_t$ given $I_0,\dots,I_{t-1}$, the infectivity profile $\omega$ and $R_{t,\tau}$. To do this we restate the posterior probability  the relationship $P(A \cup B) = P(A|B)P(B)$ in two stages, firstly:

$$
\begin{aligned}

P(R_{t,\tau} | I_0,\dots,I_{t},\omega)  &= 
\frac{P(R_{t,\tau}, I_0,\dots,I_{t},\omega)}
{P(I_0,\dots,I_{t},\omega)}\\
\end{aligned}
$$

And secondly:

$$
\begin{aligned}
P(R_{t,\tau}, I_0,\dots,I_{t},\omega) &=
P(R_{t,\tau}, I_{t-\tau+1}, \dots,I_{t}|I_0, \dots,I_{t-\tau},\omega)P(I_0, \dots,I_{t-\tau},\omega)
\\
\end{aligned}
$$

Substituting and re-organising:

$$
\begin{aligned}
P(R_{t,\tau} | I_0,\dots,I_{t},\omega)
\frac{P(I_0,\dots,I_{t},\omega)}
{P(I_0, \dots,I_{t-\tau},\omega)}
&= P(R_{t,\tau}, I_{t-\tau+1}, \dots,I_{t}|I_0, \dots,I_{t-\tau},\omega)
\\
\end{aligned}
$$

We have evidence $P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega,R_{t,\tau})$ and prior belief $P(R_{t,\tau})$, and we can relate these to the right hand side of the previous expression:

$$
\begin{aligned}
P(R_{t,\tau}, I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega) &= 
\frac{
P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega,R_{t,\tau})
P(R_{t,\tau})
}{
  P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega)
} \\
\end{aligned}
$$
And combining these two expressions gives us:

$$
\begin{aligned}
P(R_{t,\tau} | I_0,\dots,I_{t},\omega)
\frac{P(I_0,\dots,I_{t},\omega)}
{P(I_0, \dots,I_{t-\tau},\omega)}
&=\frac{
P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega,R_{t,\tau})
P(R_{t,\tau})
}{
  P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega)
} \\
\end{aligned}
$$

This includes components which are not conditional in any way on $R_t$. Given $I_0,\dots,I_{t},\omega$ these are constant:

$$
\frac{P(I_0, \dots,I_{t-\tau},\omega)}
{P(I_0,\dots,I_{t},\omega)P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega)} = K\\
$$

Which gives us the following expression for the posterior of $R_t$ given our prior belief and the evidence:

$$
\begin{aligned}
P(R_{t,\tau} | I_0,\dots,I_{t},\omega)  &= K 
P(I_{t-\tau+1}, \dots,I_t | I_0,\dots,I_{t-\tau},\omega,R_{t,\tau})
P(R_{t,\tau})
\end{aligned}
$$
Using the expressions for the likelihood, and the prior probability derived above:

$$
\begin{aligned}
P(R_{t,\tau} | I_0,\dots,I_{t},\omega,\alpha,\beta)  &= K
\Bigg(
  \prod_{s=t-\tau+1}^t\frac{(R_{t,\tau}\Lambda_t)^{I_s}e^{-R_{t,\tau}\Lambda_s}}{I_s!}
\Bigg)
\Bigg(
  \frac{\beta^\alpha}{\Gamma(\alpha)} R_{t,\tau}^{\alpha-1}e^{-\beta R_{t,\tau}}
\Bigg)
\\
&=
KR_{t,\tau}^{\alpha+\sum_{s=t-\tau+1}^t I_s-1}e^{-R_{t,\tau}\big(\beta+\sum_{s=t-\tau+1}^t \Lambda_s\big)}
\Bigg(
  \prod_{s=t-\tau+1}^t\frac{\Lambda_s^{I_s}}{I_s!}
\Bigg)
\Bigg(
  \frac{\beta^\alpha}{\Gamma(\alpha)}
\Bigg)
\end{aligned}
$$

Which we noting has a form similar to a gamma with shape $\alpha'$ and scale $\beta'$:

$$
\begin{aligned}
\alpha' &= \alpha+\sum_{s=t-\tau+1}^t I_s \\
\beta' &= \beta+\sum_{s=t-\tau+1}^t \Lambda_s\\
\end{aligned}
$$

Leads us to the conclusion that the posterior distribution of $R_t$ is Gamma distributed, with shape ($\alpha'$) and rate  ($\beta'$) with a constant factor:


$$
\begin{aligned}
P(R_{t,\tau} | I_0,\dots,I_{t},\omega) &=  
\frac{
  {\beta'}^{\alpha'}
}{
 \Gamma({\alpha'})
}
R_{t,\tau}^{{\alpha'}-1}e^{-R_{t,\tau}{\beta'}}
K\Bigg(
  \prod_{s=t-\tau+1}^t\frac{\Lambda_s^{I_s}}{I_s!}
\Bigg)
\Bigg(
  \frac{
    \Gamma(\alpha')\beta^\alpha
  }{
    \Gamma(\alpha){\beta'}^{\alpha'}
  }
\Bigg)\\
R_{t,\tau} | I_0,\dots,I_{t},\omega &\sim Gamma\Big(\alpha+\sum_{s=t-\tau+1}^t I_s, \beta+\sum_{s=t-\tau+1}^t \Lambda_s\Big)
\end{aligned}
$$





