---
title: "Getting started"
author: "Rob Challen"
date: "03/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE
)

here::i_am("vignettes/getting-started.Rmd")
source(here::here("vignettes/common-setup.R"))
```

## a simulated dataset


```{r}


a = ggplot()+
  geom_line(data = simpleDataset$ts, mapping = aes(x=date, y=Growth.actual), colour="red")+
  geom_point(data = simpleDataset$events, mapping = aes(x=`Start date`, y=rates), colour="red")

b = ggplot() +
  geom_bar(data=simpleDataset$ts, mapping=aes(x=date,y=import), stat="identity", position = "dodge")+
  geom_line(data=simpleDataset$ts, mapping=aes(x=date,y=Est.actual), colour="red")+ylab("Cases")+
  geom_line(data=simpleDataset$ts, mapping=aes(x=date,y=value), colour="black",size=0.1,alpha=0.3)+
  geom_point(data=simpleDataset$ts %>% filter(bootstrap==1), mapping=aes(x=date,y=value), colour="black",size=0.1)

a+ggrrr::gg_hide_X_axis()+b+patchwork::plot_layout(ncol=1)

test = jepidemic::simpleDataset$ts %>% filter(bootstrap==1)
infProf = jepidemic::simpleDataset$infectivityProfile

```

## growth rate estimate + rt from growth rate

```{r}
gr = test %>% filter(bootstrap==2) %>% locfitGrowthEstimate()

ggplot(gr)+
  geom_rect(aes(xmin=date,xmax=date+1,alpha=import),ymin=-Inf,ymax=Inf,fill="blue")+
  scale_alpha_continuous(range=c(0,0.3))+
  geom_line(aes(x=date,y=Growth.Quantile.0.5), colour="black")+
  geom_ribbon(aes(x=date,ymin=Growth.Quantile.0.025,ymax=Growth.Quantile.0.975), fill="grey",alpha=0.2)+
  geom_line(aes(x=date,y=Growth.actual), colour="red")+
  coord_cartesian(ylim=c(-0.15,0.15))
  

```

```{r}
rt = gr %>% rtFromGrowthRate(infProf)

ggplot(rt)+
  geom_rect(aes(xmin=date,xmax=date+1,alpha=import),ymin=-Inf,ymax=Inf,fill="blue")+
  scale_alpha_continuous(range=c(0,0.3))+
  geom_line(aes(x=date,y=Rt.Quantile.0.5), colour="black")+
  geom_ribbon(aes(x=date,ymin=Rt.Quantile.0.025,ymax=Rt.Quantile.0.975), fill="grey",alpha=0.2)+
  geom_line(aes(x=date,y=Rt.actual), colour="red")+
  coord_cartesian(ylim=c(0.75,1.5))

```
# Rt via cori method:

```{r}

estim1 = J$CoriEstimator$new(r0Mean = 1.2,r0SD = 4,maxWindow = 14)
estim1$withInfectivityProfileMatrix(infProf$yMatrix)
estim1$inMiddleOfTimeseries()
estim1$withAdaptivePrior(factor = 1.25)
estim1$selectMixtureCombination()
estim1$collectMixtureApproximation()
cori = estim1$estimateRt(test, dateColName = "date",incidenceColName = "value") %>% mutate(date = Rt.EndDate)


ggplot(cori)+
  geom_rect(data=test, mapping=aes(xmin=date,xmax=date+1,alpha=import),ymin=-Inf,ymax=Inf,fill="blue")+
  scale_alpha_continuous(range=c(0,0.3))+
  geom_line(aes(x=date,y=Rt.Quantile.0.5), colour="black")+
  geom_ribbon(aes(x=date,ymin=Rt.Quantile.0.025,ymax=Rt.Quantile.0.975), fill="grey",alpha=0.2)+
  geom_line(data=test, mapping=aes(x=date,y=Rt.actual), colour="red")+
  coord_cartesian(ylim=c(0.75,1.5))

```
# Bayesian estimators

```{r}
grEstim = J$GrowthRateEstimator$new(minWindow = 4,maxWindow = 21)
# grEstim$priorIncidenceFromPosteriorMean()
# grEstim$combineEstimatesWithWeightedMixture()
# grEstim$useAllPosteriorEstimates()
grEstim$withSaneDefaults()
grEstim$withInfectivityProfileMatrix(infProf$yMatrix)
out = grEstim$estimateGrowthRateSingle(test, dateColName = "date",incidenceColName = "value")

ggplot(out)+
  geom_rect(data=test, mapping=aes(xmin=date,xmax=date+1,alpha=import),ymin=-Inf,ymax=Inf,fill="blue")+
  scale_alpha_continuous(range=c(0,0.3))+
  geom_line(aes(x=date,y=Est.Quantile.0.5), colour="black")+
  geom_ribbon(aes(x=date,ymin=Est.Quantile.0.025,ymax=Est.Quantile.0.975), fill="grey",alpha=0.2)+
  geom_line(data=test, mapping=aes(x=date,y=Est.actual), colour="red")+
  geom_point(data=test, mapping=aes(x=date,y=Est.observed), colour="red",size=0.2)

ggplot(out)+
  geom_rect(data=test, mapping=aes(xmin=date,xmax=date+1,alpha=import),ymin=-Inf,ymax=Inf,fill="blue")+
  scale_alpha_continuous(range=c(0,0.3))+
  geom_line(aes(x=date,y=Rt.Quantile.0.5), colour="black")+
  geom_ribbon(aes(x=date,ymin=Rt.Quantile.0.025,ymax=Rt.Quantile.0.975), fill="grey",alpha=0.2)+
  geom_line(data=test, mapping=aes(x=date,y=Rt.actual), colour="red")+
  coord_cartesian(ylim=c(0.75,1.5))

ggplot(out)+
  geom_rect(data=test, mapping=aes(xmin=date,xmax=date+1,alpha=import),ymin=-Inf,ymax=Inf,fill="blue")+
  scale_alpha_continuous(range=c(0,0.3))+
  geom_line(aes(x=date,y=Growth.Quantile.0.5), colour="black")+
  geom_ribbon(aes(x=date,ymin=Growth.Quantile.0.025,ymax=Growth.Quantile.0.975), fill="grey",alpha=0.2)+
  geom_line(data=test, mapping=aes(x=date,y=Growth.actual), colour="red")+
  coord_cartesian(ylim=c(-0.15,0.15))
```