---
title: "Appendix B - Incidence and growth rate estimation"
author: "Rob Challen"
date: '`r format(Sys.Date(), "%d-%m-%Y")`'
output: 
  pdf_document :
    fig_caption: yes
header-includes:
 \usepackage{float}
 \usepackage{mathtools}
 \usepackage{amsmath}
 \DeclareRobustCommand{\[}{\begin{equation*}}
 \DeclareRobustCommand{\]}{\end{equation*}}
 \newcounter{tagno}
 \setcounter{tagno}{0}
 \let\amsmathtag\tag
 \renewcommand{\tag}[1]{\amsmathtag{\thetagno} \label{#1} \stepcounter{tagno}}
 \floatplacement{figure}{H}    
knit: (function(inputFile, encoding,...) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "~/Dropbox/sarscov2/r-estimation-methodology", output_file=paste0('incidence-and-growth-rate-',Sys.Date(),'.pdf')) })
fig_width: 7
fig_height: 5
out.width: "100%"
bibliography: jepidemic.bib
csl: jepidemic.csl
vignette: >
  %\VignetteIndexEntry{Cori method}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The effective reproduction number ($R_t$) is a useful measure of the state of the epidemic but by itself does not inform us of the likely impact that the epidemic will have. To do that we need an unbiased estimator of case counts. As the reproduction number is conditioned on the infectivity profile $\omega$ the timing of that impact is also not described by the reproduction number. For this a more useful measure is the real-time growth rate ($r_t$), which it has been argued are more informative for decision making [CITE PELLIS], as combined with case counts it can inform how quickly cases will reach certain thresholds when intervention is required. The reproduction number implicitly describes a closed population, which when describing sub-populations may be unhelpful. The growth rate can be inferred directly from data and this does not require sophisticated models.

In this appendix we describe the approach to estimation the real-time growth rate adopted throughout the majority of this thesis.

## Estimating incidence and growth rate.

Assume $I_0, I_1, \dots, I_t$ is a time series of infection counts, drawn from some discrete probability distribution with expected value $\overline{I_t}$. The epidemic growth process is exponential by nature. The real-time growth rate reflect this as is defined as the rate of change of the logarithm of infections:

$$
\begin{aligned}
\overline{I_{t+\Delta t}} &= \overline{I_{t}}e^{r_t\Delta t} \\
r_t &= \frac{ log(\overline{I_{t+\Delta t}}) - log(\overline{I_{t}})}{\Delta t} \\
r_t &= \frac{d log(\overline{I_t})}{dt} \\
\end{aligned} \tag{eq:littleR}
$$

We assume $I_t$ is a Poisson distributed quantity, with a rate parameter which is a function of time:

$$
\begin{aligned}
I_t &\sim Poisson(\lambda_t) \\
\overline{I_t} &= \lambda_t \\
r_t &= \frac{dlog(\lambda_t)}{dt}
\end{aligned}
$$
Due to the probability density function underlying the Poisson distribution estimating both $\overline{I_t}$ and $r_t$ from data is straightforward, in a range of frameworks. Following the methods of Loader et al. [CITE] we represent $\lambda_t$ as a polynomial function of time, and adopt a local maximum likelihood estimator with a logarithmic link function such that:

$$
\begin{aligned}
I = g(y) &= e^{y}\\
y = g^{-1}(I) &= log(I)\\
y_t(t_i) = \langle a, A(t_i-t)\rangle &= a_0 + a_1(t_i-t)+ \dots + a_n(t_i-t)^n\\
l(y,\lambda) &= log(P(y|\lambda))\\
\end{aligned}
$$
The global log-likelihood of a set of $\lambda$ estimates $\lambda_0, \lambda_1, \dots, \lambda_n$ is then given by:

$$
\mathcal{L}(\lambda) = \sum_{i=1}^nl(Y_i, \lambda_i)
$$

A corresponding localised log-likelihood function evaluated at time $t$ can be created using a local kernel function $w$.

$$
\mathcal{L}_t(\lambda) = \sum_{i=1}^nw_i(t) .l(Y_i, \langle a, A(t_i-t)\rangle)
$$

Which is maximised over the parameter set $a$, to generate a local estimate of the polynomial. From this direct estimates of the local $\overline{I_t}$ and $r_t$ are given by:

$$
\overline{I_t} = e^{a_0}\\
r_t = \frac{dA}{dt}(t) = a_1
$$

The local kernel function is by default chosen to be a tri-cube function truncated between -1 and 1 and applied to a window of the data defined by a bandwidth $n$. Bandwidth selection can be done both as a range of $t-n/2 \dots t+n/2$ entries withing the time series or the nearest $n$ data points: 

$$
w_i(u) = \Big(1-\Big|\frac{i-u}{n}\Big|^3\Big)^3
$$

Using this method, the incidence and growth rate estimation therefore depend on the bandwidth and the polynomial degree. Given that the most interesting part of the data is the right hand boundary, the choice of bandwidth selection method also is important, as this influences behaviour at the boundary.

The confidence of the estimates of $a$, given the logarithmic transformation are described in detail in Loader et al. {CITE] and less straightforward. The confidence estimates of predictions rely on a variance stabilising link function, and a local regression weight diagram, and an assumption of normality in the transformed space, however the derivation of the confidence intervals on the parameters themselves is not fully detailed.

## Estimating the relative growth of proportions

In some instances we have information pertaining the proportion of two classes and the challenge is to estimate the relative growth rate of one class over the other. A concrete example of this is positive and negative test results, the ratio of which allows us to estimate the absolute growth rate. This has the advantage of being less dependent on observation rates, so long as the individual classes are being observed at an equal rate. A second example is the relative growth of one SARS-CoV-2 variant over another. In this 

$$
\begin{aligned}
I_{t+1}^+ &= I_{t}^+e^{r^+_t}\\
I_{t+1}^- &= I_{t}^-e^{r^-_t}\\
N_t &= I_t^++I_t^-\\
p_t^+ &= \frac{I_t^+}{N_t} \\
r_t &= r_t^+-r_t^- \\
\end{aligned}
$$

$$
\begin{aligned}
p_{t+1} &= \frac{I_{t}^+e^{r^+_t}}{I_{t}^+e^{r^+_t} + I_{t}^-e^{r^-_t}} \\
p_{t+1} &= \frac{N_tp_te^{r^+_t}}{N_tp_te^{r^+_t} + N_t(1-p_t)e^{r^-_t}} \\
p_{t+1} &= \frac{p_te^{r^+_t}}{p_te^{r^+_t} + (1-p_t)e^{r^-_t}} \\
p_{t+1} &= \frac{p_te^{r_t}e^{r^-_t}}{p_te^{r_t}e^{r^-_t} + (1-p_t)e^{r^-_t}} \\
p_{t+1} &= \frac{p_te^{r_t}}{p_te^{r_t} + (1-p_t)} \\
p_{t+1} &= \frac{1}{1 + \frac{(1-p_t)}{p_t}e^{-r_t}} \\
\end{aligned}
$$

$$
\begin{aligned}
\frac{(1-p_t)}{p_t}e^{-r_t} &= \frac{1}{p_{t+1}} - 1 \\
\Big(\frac{1}{p_t}-1\Big)e^{-r_t} &= \frac{1}{p_{t+1}} - 1 \\
p'_te^{-r_t} & = p'_{t+1}\\
r_t & =log(p'_t)-log(p'_{t+1})\\
\end{aligned}
$$

## Estimating $R_t$ from the growth rate.

With an estimate of the growth rate available we would like to be able to make an estimate of the reproduction number, derived from this growth rate. We adopt the method of Wallinga et al. (2007) [CITE]. This describes the generation interval distribution $g(a)$ as a continuous function which describes the probability of a secondary infection related to the "age" $a$ of a primary infection, i.e. the time from primary to secondary infection. This is combined with the Lotka_euler equation [CITE] to generate the following relationship between $R$ and $r$

$$
\frac{1}{R} = \int_{a=0}^{\infty}e^{-ra}g(a)da
$$

Which is identifiable as the Laplace transformation of $g(a)$ and hence the moment generating function $M$ of the distribution $g()$. This leads to the following simplified relationship:

$$
R = \frac{1}{M(-r)}
\tag{eq:momgen}
$$

This relationship can be used to connect $R$ with $r$ for any given generation interval distribution assuming a moment generating function exists. In practice, as infection duration is measured in whole days, and in the implementation of the Cori method for estimating $R_t$ [CITE] the discrete version of the generation interval distribution is used and referred to as the infectivity profile ($\omega_1, \omega_2, \dots, \omega_a$). 

The discrete version of the relationship in $\eqref{eq:momgen}$ is derived in Wallinga et al. [CITE] and given as:

$$
R = \frac{r}{
  \sum_{i=1}^n
  \omega_i \frac{
    e^{-ra_{i-1}}-e^{-ra_{i}}
  }{
    a_i-a_{i-1}
  }
}
\tag{eq:disc}
$$
Where $a_i$ is the upper boundary of the discretisation and $a_{i-1}$ is the lower bound such that:

$$
\omega_i = \int_{a_{i-1}}^{a_i}g(a)da
$$
This allows for arbitrary discretisation intervals. In the Cori method, however, the discretisation of $\omega$ is enforced to be on whole day boundaries such that $a_0 = 0, a_1 = 1, \dots$. This simplifies $\eqref{eq:disc}$ to:

$$
R = \frac{r}{
  \sum_{i=1}^n
  \omega_i (e^{-r(i-1)}-e^{-ri})
}
$$
With our estimates of the growth rate with associated confidence limits from the first section we can combine this method with a sampling approach to generate an alternative estimate for the reproduction number.

